### ISSUE TITLE
** Update drizzle current account **

### ISSUE THREAD

**Issue by dheerajpoonia29** [dheerajpoonia29/paintingProcurementPortal-finalYearProject#1]
problem is that when we select the other account of metmask then drizzle won't update it

**Comment by rduttshukla** [comment]
We can try using `web3.eth.getAccounts()` method anywhere to get a list of accounts. The account at index 0 should be the current account. Although I haven't found no information regarding the order of accounts returned by `web3.eth.getAccounts()` online so we'll have to give it a try.

P.S.: `web3.eth.getBalance('account_address')` gives the balance of the account passed in the argument

**Comment by rduttshukla** [comment]
Implemented with `window.ethereum` and web3
